version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: teddy-test-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: teddy-test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
